spring:
  config:
    activate:
      on-profile: test

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-maser.yml

  datasource:
    url: jdbc:mysql://localhost:3306/distance-calculator
    username: root
    password: root
    name: distance-calculator

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
